# Generated by Django 2.1.7 on 2023-07-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=20)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_unit', models.CharField(max_length=20)),
                ('product_code', models.CharField(max_length=20)),
                ('price', models.FloatField(null=True)),
                ('cost', models.FloatField(null=True)),
                ('inventory_quantity', models.PositiveIntegerField(default=None, null=True)),
                ('sales_region', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFollowUpLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_person', models.CharField(max_length=20)),
                ('sales_quantity', models.CharField(max_length=20)),
            ],
        ),
    ]
