# Generated by Django 2.1.7 on 2023-07-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfollowuplog',
            name='product_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='productfollowuplog',
            name='sales_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='productfollowuplog',
            name='sales_person',
            field=models.PositiveIntegerField(),
        ),
    ]
