# Generated by Django 2.1.7 on 2023-07-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230714_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfollowuplog',
            name='sales_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
